### ISSUE TITLE
 cert-manager  Error presenting challenge: Failed to validate config: secrets   is forbidden: User "system:serviceaccount:cert-manager:godaddy-webhook" cannot get resource "secrets" in API group "" in the namespace "cert-manager"

### ISSUE THREAD

**Issue by jackliusr** [jackliusr/cert-manager-webhook-godaddy#1]
``` yaml
dns01:`
        webhook:
          config:
            authApiKey: <your GoDaddy authAPIKey>
            authApiSecretRef: 
                name: <Secret Name>
                key: <key in secret>
            production: true
            ttl: 600
```
